version: '3.1'
services:
  iapps_app:
    image: 'iapps:latest'
    build:
      context: .
    container_name: iapps_app
    depends_on:
      - iapps_db
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://iapps_db:5432/postgres
    expose:
      - "9090"
          
  iapps_db:
    image: 'postgres:13.1-alpine'
    container_name: iapps_db
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
